stages:          # List of stages for jobs, and their order of execution
  - build

package-job:       # This job runs in the build stage, which runs first.
  stage: build
  script: 
    - npm install -f
    - CI=false npm run build 
    - rm -rf /opt/frontend-gadel/*
    - mv ./build/* /opt/frontend-gadel/
